//create
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Rifki",
  "email": "admin@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "role": "admin"
}

###
//get all users
GET http://localhost:5000/users

###
//get user by id
GET http://localhost:5000/users/5f30a1e2-987a-45b8-a2ac-6b9462140ed6


###
//update user
PATCH  http://localhost:5000/users/5f30a1e2-987a-45b8-a2ac-6b9462140ed6
Content-Type: application/json

{
  "name": "Rifki Updated",
  "email": "rifki@gmail.com",
  "password": "",
  "confirmPassword": "",
  "role": "user"
}

###
//delete user
DELETE  http://localhost:5000/users/5f30a1e2-987a-45b8-a2ac-6b9462140ed6

###
//login
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "ici@gmail.com",
  "password": "123456"
}

###
//Me
GET http://localhost:5000/me

###
//logout
DELETE http://localhost:5000/logout

###
//get all products
GET http://localhost:5000/products

###
//get single products
GET http://localhost:5000/products/b5eddeea-cd44-458c-973e-1e244316d741

###
// POST data products
POST http://localhost:5000/products
Content-Type: application/json

{
  "name": "Product 7",
  "price": 99510
}

###
// updated data product
PATCH http://localhost:5000/products/0a86049a-5423-4613-a70a-5785a8c3f345
Content-Type: application/json

{
  "name": "Product Updated",
  "price": 9999
}

###
//delete data product
DELETE http://localhost:5000/products/b5eddeea-cd44-458c-973e-1e244316d741